### PR TITLE
Exercices 4 to 7

### PR DESCRIPTION
**Pull request by superbionicle**

### CODE REVIEW

**Comment by RoccoA97** [comment]
Hi @superbionicle,

Could you please delete all the garbage/data files that are under `data/`? We just need the exercise notebooks.
After that, I'll merge

**Comment by RoccoA97** [comment]
Hi @superbionicle,

Please remove .DS_store and then I'll merge

**Comment by RoccoA97** [comment]
Hi @superbionicle 

Not sure what you are doing, but you don't need to force-push stuff.
I still see the .DS_store in this PR.

A `git rm daa/.DS_store` + commit + push (NOT FORCE PUSH) should be sufficient, no?
Anyway, I consider Friday the last available day to merge the second homework, so please update as soon as possible

**Comment by superbionicle** [comment]
> Hi @superbionicle
> 
> Not sure what you are doing, but you don't need to force-push stuff. I still see the .DS_store in this PR.
> 
> A `git rm daa/.DS_store` + commit + push (NOT FORCE PUSH) should be sufficient, no? Anyway, I consider Friday the last available day to merge the second homework, so please update as soon as possible

It should be done now

**Pull request merged**
