### PR TITLE
First 3 exercises

### PR DESCRIPTION
**Pull request by ElnazDt**
Here are first 3 exercises. they where done by the deadline, but I did not know that I had to open a pull request.

### CODE REVIEW

**Comment by RoccoA97** [comment]
Hi @ElnazDt,

Do not point the PR to the `main` branch of the upstream.
Please, **edit** it so that it points to your personal branch in the upstream.

About the deadline, it has been clearly said during the course this was the way to submit the exercises and the deadline for the first block was remarked several times.
We will accept the exercises but we'll take into account the delay (nothing too significant though)

**Comment by zucchett** [comment]
Dear Elnaz, this is the last warning. Either by the end of this week the PR is fixed (pointing to the proper branch) or we will close the PR and will consider the set of exercises as missing. This would also mean that you do not qualify for the final exam. Please fix this ASAP.

**Comment by zucchett** [comment]
Dear Elnaz, this is a reminder that the PR is still incomplete.

**Comment by ElnazDt** [comment]
Dear professor, I made a new PR an hour ago with the correct branch and direction. the PR name is Elnaz D.

**Comment by RoccoA97** [comment]
Hi @ElnazDt,

Is this an old PR? I remember we have merged few weeks ago a PR opened by you

**Comment by ElnazDt** [comment]
Hello @RoccoA97 ,
this was a wrong PR that I opened by mistake.
I opened a correct PR after this for first 3 exercises and it was merged.

**Pull request closed without merging**
