### PR TITLE
Solutions up to 11th exercise

### PR DESCRIPTION
**Pull request by luciozebendo**

### CODE REVIEW

**Comment by zucchett** [comment]
Please do not point the PR to the proper branch of the upstream repository (not the main)

**Comment by luciozebendo** [comment]
> Please do not point the PR to the proper branch of the upstream repository (not the main)

Done!

**Comment by RoccoA97** [comment]
Hi @luciozebendo 

Looks like from ex04 to ex11 everything is in python .py script. Could you convert to notebooks?
Another question, the 2nd set of exercises has changes in this PR. But I see that you did not deliver the second set of exercises in the past months

**Comment by luciozebendo** [comment]
> Hi @luciozebendo
> 
> Looks like from ex04 to ex11 everything is in python .py script. Could you convert to notebooks? Another question, the 2nd set of exercises has changes in this PR. But I see that you did not deliver the second set of exercises in the past months

Hello! Sure, I changed all .py to .ipynb. About the second question, I talked to the professor during class, I had a problem on the pull request.

**Pull request merged**
