### PR TITLE
Yekaterina muradyan

### PR DESCRIPTION
**Pull request by miakate**
Second Homework

### CODE REVIEW

**Comment by RoccoA97** [comment]
Hi @miakate 

The PR was submitted after the deadline, so a penalty will be applied.
Merging

**Comment by zucchett** [comment]
Also please remove all data files, images, notebooks of the lectures, etc. that are not essential for the exercises

**Comment by RoccoA97** [comment]
Hi @miakate,

Could you please update? We need to merge this

**Comment by miakate** [comment]
Yes sure, today i will push an update!
 Thank you

**Comment by RoccoA97** [comment]
@miakate,

Any news? I consider Friday the last available day to merge this

**Comment by miakate** [comment]
> @miakate,
> 
> Any news? I consider Friday the last available day to merge this

I apologize for the delay in submitting my homework. I experienced some technical issues with my system, but I have resolved them now. I believe everything is in order, and I appreciate your understanding.

Thank you for your patience.

**Comment by RoccoA97** [comment]
Hi @miakate 

Looks like you have converted also the first set of exercises. I asked you to provide the notebooks for the second set...
Could you revert the change for the first set of exercises (these have to stay untouched with respect to the previous PR)

**Comment by miakate** [comment]
> Hi @miakate
> 
> Looks like you have converted also the first set of exercises. I asked you to provide the notebooks for the second set... Could you revert the change for the first set of exercises (these have to stay untouched with respect to the previous PR)

updated!

**Pull request merged**
