### PR TITLE
Yekaterina muradyan

### PR DESCRIPTION
**Pull request by miakate**

### CODE REVIEW

**Comment by RoccoA97** [comment]
Hi @miakate,

You are pointing the PR to the `main` branch of the upstream.
Please don't do that, there is a dedicated branch `yekaterina_muradyan` for your exercises.
Could you point the PR to that branch?

**Comment by miakate** [comment]
Good morning, I have a problem my problem is that I don't see my updates in
this repo https://github.com/zucchett/ScientificComputingWithPython2023 but
I see them in the forked one here
https://github.com/miakate/ScientificComputingWithPython2023/tree/yekaterina_muradyan
.

is it a problem should I change it?

**Comment by RoccoA97** [comment]
@miakate 

It's normal, because the PR has the purpose to merge your commits (namely your exercises) to
https://github.com/zucchett/ScientificComputingWithPython2023/tree/yekaterina_muradyan

But before that, please change the PR so that it points to `zucchett:yekaterina_muradyan`, otherwise I can't accept the merge.

**Comment by miakate** [comment]
Yes sure i will try to change, the deadline is 3 of November, its means 3
including(not today until 00) just to make sure i have time

**Comment by RoccoA97** [comment]
Until November 3, 23:59

**Comment by miakate** [comment]
Thanks a lot)

**Comment by RoccoA97** [comment]
Hi @miakate,

The PR is still pointing to `zucchett:main`, please change that otherwise I can't close it.
As I have already told you, you have to point it to `zucchett:yekaterina_muradyan`...

**Pull request closed without merging**
