### PR TITLE
HW2

### PR DESCRIPTION
**Pull request by chaharlangi**

### CODE REVIEW

**Comment by RoccoA97** [comment]
@chaharlangi 

Please remove all the unnecessary data files.
I just need the .py and .ipynb

Friday is the last day to merge this, so please, update it as soon as possible

**Comment by chaharlangi** [comment]
> @chaharlangi
> 
> Please remove all the unnecessary data files. I just need the .py and .ipynb
> 
> Friday is the last day to merge this, so please, update it as soon as possible

Hi @RoccoA97 

Sorry for that, I removed all unnecessary files. It is now complying with the main repository and includes the images folder as well.

**Comment by zucchett** [comment]
Hi @chaharlangi , please remove the images, too. We just need the .py or .ipynb files.

**Comment by chaharlangi** [comment]
@zucchett I've just done it, thanks

**Pull request merged**
